import 'package:tekblog_application_4/Model/data_models.dart';
import 'package:tekblog_application_4/gen/assets.gen.dart';

Map homePagePosterMap = {

  "imageAsset" : Assets.images.posterTest.path,
  "writer" : "مبین عبدالهی",
  "date" : "یک روز پیش",
  "title" : "دوازده قدم برنامه نویسی . یک دوره",
  "view" : "251"


};
// blog fake data

List<HashTagModel> tagList = [


  HashTagModel(title: "جاوا"),
  HashTagModel(title: "کاتلین"),
  HashTagModel(title: "وب"),
  HashTagModel(title: "هوش مصنوعی"),
  HashTagModel(title: "iot"),
  HashTagModel(title: "دارت"),


];  

List<BlogModel> blogList = [
  BlogModel(
    id: 0,
    imageUrl: "https://picsum.photos/seed/code1/800/600",
    title: "Flutter چیست و چرا بهترین انتخاب برای ساخت اپلیکیشن‌های موبایل است؟",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user1/100/100",
    date: "1403/10/01",
    content: "آشنایی کامل با فریم‌ورک Flutter",
    view: "245",
  ),
  BlogModel(
    id: 1,
    imageUrl: "https://picsum.photos/seed/code2/800/600",
    title: "شروع برنامه نویسی از صفر؛ اولین قدم‌ها برای ورود به دنیای کدنویسی",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user2/100/100",
    date: "1403/10/02",
    content: "قدم‌های اولیه برای ورود به برنامه نویسی",
    view: "312",
  ),
  BlogModel(
    id: 2,
    imageUrl: "https://picsum.photos/seed/code3/800/600",
    title: "زبان Dart چیست و چرا قلب تپنده فریم‌ورک Flutter محسوب می‌شود؟",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user3/100/100",
    date: "1403/10/03",
    content: "یادگیری زبان Dart مخصوص Flutter",
    view: "421",
  ),
  BlogModel(
    id: 3,
    imageUrl: "https://picsum.photos/seed/code4/800/600",
    title: "چگونه رابط کاربری زیبا و حرفه‌ای در Flutter طراحی کنیم؟",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user4/100/100",
    date: "1403/10/04",
    content: "طراحی رابط کاربری حرفه‌ای",
    view: "198",
  ),
  BlogModel(
    id: 4,
    imageUrl: "https://picsum.photos/seed/code5/800/600",
    title: "State Management در Flutter چیست و چرا یادگیری آن ضروری است؟",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user5/100/100",
    date: "1403/10/05",
    content: "مدیریت وضعیت در Flutter",
    view: "534",
  ),
  BlogModel(
    id: 5,
    imageUrl: "https://picsum.photos/seed/code6/800/600",
    title: "مقایسه کامل GetX و Provider؛ کدام برای پروژه Flutter مناسب‌تر است؟",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user6/100/100",
    date: "1403/10/06",
    content: "مقایسه روش‌های مدیریت وضعیت",
    view: "289",
  ),
  BlogModel(
    id: 6,
    imageUrl: "https://picsum.photos/seed/code7/800/600",
    title: "آموزش ListView در Flutter؛ نمایش لیست‌ها به صورت حرفه‌ای و بهینه",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user7/100/100",
    date: "1403/10/07",
    content: "کار با لیست‌ها در Flutter",
    view: "367",
  ),
  BlogModel(
    id: 7,
    imageUrl: "https://picsum.photos/seed/code8/800/600",
    title: "Navigation در Flutter؛ جابجایی بین صفحات به روش استاندارد و اصولی",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user8/100/100",
    date: "1403/10/08",
    content: "مسیریابی بین صفحات",
    view: "414",
  ),
  BlogModel(
    id: 8,
    imageUrl: "https://picsum.photos/seed/code9/800/600",
    title: "API چیست و چگونه اپلیکیشن Flutter را به سرور متصل کنیم؟",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user9/100/100",
    date: "1403/10/09",
    content: "ارتباط با سرور و API",
    view: "652",
  ),
  BlogModel(
    id: 9,
    imageUrl: "https://picsum.photos/seed/code10/800/600",
    title: "کار با JSON در Flutter؛ دریافت، تبدیل و مدیریت داده‌ها",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user10/100/100",
    date: "1403/10/10",
    content: "دریافت و پردازش داده‌ها",
    view: "231",
  ),
  BlogModel(
    id: 10,
    imageUrl: "https://picsum.photos/seed/code11/800/600",
    title: "آموزش احراز هویت کاربران؛ پیاده‌سازی Login و Register در اپلیکیشن‌ها",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user11/100/100",
    date: "1403/10/11",
    content: "Login و Register در اپلیکیشن‌ها",
    view: "778",
  ),
  BlogModel(
    id: 11,
    imageUrl: "https://picsum.photos/seed/code12/800/600",
    title: "Firebase چیست و چگونه از آن در پروژه‌های Flutter استفاده کنیم؟",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user12/100/100",
    date: "1403/10/12",
    content: "استفاده از Firebase در Flutter",
    view: "498",
  ),
  BlogModel(
    id: 12,
    imageUrl: "https://picsum.photos/seed/code13/800/600",
    title: "چگونه از اپلیکیشن Flutter خروجی اندروید و iOS بگیریم؟",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user13/100/100",
    date: "1403/10/13",
    content: "خروجی گرفتن برای اندروید و iOS",
    view: "356",
  ),
  BlogModel(
    id: 13,
    imageUrl: "https://picsum.photos/seed/code14/800/600",
    title: "آشنایی با Clean Architecture؛ ساخت پروژه‌های مقیاس‌پذیر و حرفه‌ای",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user14/100/100",
    date: "1403/10/14",
    content: "معماری تمیز در پروژه‌ها",
    view: "612",
  ),
  BlogModel(
    id: 14,
    imageUrl: "https://picsum.photos/seed/code15/800/600",
    title: "دیباگ در Flutter؛ پیدا کردن و رفع خطاهای رایج در پروژه‌ها",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user15/100/100",
    date: "1403/10/15",
    content: "رفع خطاهای رایج",
    view: "189",
  ),
  BlogModel(
    id: 15,
    imageUrl: "https://picsum.photos/seed/code16/800/600",
    title: "افزایش Performance اپلیکیشن‌های Flutter با تکنیک‌های بهینه‌سازی",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user16/100/100",
    date: "1403/10/16",
    content: "بهینه‌سازی سرعت برنامه",
    view: "344",
  ),
  BlogModel(
    id: 16,
    imageUrl: "https://picsum.photos/seed/code17/800/600",
    title: "راهنمای کامل انتشار اپلیکیشن Flutter در مارکت‌های داخلی و خارجی",
    writer: "مبین عبدالهی",
    writerImageUrl: "https://picsum.photos/seed/user17/100/100",
    date: "1403/10/17",
    content: "منتشر کردن برنامه در بازار",
    view: "521",
  ),
];


